#=====================================#
# You can edit joinmsg, join title, joinsubtitle,    #
# broadcastmsg, meetup world.                          #
# Credits: @hexyyy                                                 #
# Website: laststyle.tk                                           #
#=====================================#

# Meetup World #

World: "Meetup"


# Messages and Popups #

PlayerJoinMsg: "You joined on the meetup."
JoinSubtitle: "Kit recived"
JoinTitle: "Meetup event"
BroadcastMsg: "Joined"


